# Generated by Django 4.2.4 on 2023-08-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=60)),
                ('order', models.IntegerField(db_column='nb_order')),
                ('testament', models.CharField(choices=[('N', 'New'), ('O', 'Old')], db_column='cs_testament', default='O', max_length=1)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='nb_number')),
                ('chronology', models.IntegerField(db_column='nb_chronology')),
                ('book', models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.DO_NOTHING, to='core.book')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=40)),
                ('start_date', models.DateField(db_column='dt_start_date')),
                ('end_date', models.DateField(db_column='dt_end_date')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('period', models.IntegerField(db_column='nb_period')),
                ('pause', models.IntegerField(db_column='nb_pause')),
                ('reading_type', models.CharField(choices=[('1', 'Front To Back'), ('2', 'Chronology'), ('3', 'Parallel')], db_column='cs_reading_type', default='2', max_length=1)),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='tx_username', max_length=100)),
                ('password', models.CharField(db_column='tx_password', max_length=40)),
                ('date_registration', models.DateTimeField(db_column='dt_date_registration')),
                ('phone', models.CharField(db_column='tx_phone', max_length=32)),
                ('email', models.CharField(db_column='tx_email', max_length=128)),
                ('user_type', models.CharField(choices=[('1', 'Coordinator'), ('2', 'Advisor'), ('3', 'Ga Leader'), ('4', 'Headed')], db_column='cs_user_type', default='4', max_length=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='dt_date')),
                ('chapter', models.ForeignKey(db_column='id_chapter', on_delete=django.db.models.deletion.DO_NOTHING, to='core.chapter')),
                ('event', models.ForeignKey(db_column='id_event', on_delete=django.db.models.deletion.DO_NOTHING, to='core.event')),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='rule',
            field=models.ForeignKey(db_column='id_rule', on_delete=django.db.models.deletion.DO_NOTHING, to='core.rule'),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='dt_date')),
                ('plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='core.plan')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
            options={
                'db_table': 'control',
            },
        ),
    ]
